In [1]:
import numpy as np



In [2]:
# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

# Input dataset (4 samples, 3 features)
inputs = np.array([[0, 0, 1],
                   [1, 1, 1],
                   [1, 0, 1],
                   [0, 1, 1]])



In [3]:
inputs

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [4]:
# Output dataset (4 samples, 1 output each)
outputs = np.array([[0], [1], [1], [0]])

outputs

array([[0],
       [1],
       [1],
       [0]])

In [5]:
# Set random seed for reproducibility
np.random.seed(1)

# Initialize weights randomly with mean 0
weights_input_hidden = 2 * np.random.random((3, 4)) - 1
weights_hidden_output = 2 * np.random.random((4, 1)) - 1

# Learning rate
learning_rate = 0.1

# Training the network for 10000 epochs
for epoch in range(10000):
    # Feedforward
    hidden_input = np.dot(inputs, weights_input_hidden)
    hidden_output = sigmoid(hidden_input)
    
    final_input = np.dot(hidden_output, weights_hidden_output)
    final_output = sigmoid(final_input)
    
    # Backpropagation
    output_error = outputs - final_output
    output_delta = output_error * sigmoid_derivative(final_output)
    
    hidden_error = output_delta.dot(weights_hidden_output.T)
    hidden_delta = hidden_error * sigmoid_derivative(hidden_output)
    
    # Update weights
    weights_hidden_output += hidden_output.T.dot(output_delta) * learning_rate
    weights_input_hidden += inputs.T.dot(hidden_delta) * learning_rate

# Output after training
print("Output after training:")
print(final_output)


Output after training:
[[0.01860547]
 [0.97979541]
 [0.98184187]
 [0.01516256]]
